name: WizardsPlugin
api-version: 1.20
version: 0.20
main: WizardsGame.WizardsPlugin
description: Wizards Minigame
author: hareesun
commands:
  toggleinfinitemana:
    description: toggle infinite mana
    aliases: mana
    permission: op
    permission-message: You do not have permission!
    usage: /togglemana
  togglecooldowns:
    description: toggle cooldowns
    aliases: cooldowns
    permission: op
    permission-message: You do not have permission!
    usage: /togglecooldowns
  checkmana:
    description: check mana
    aliases: chmana
    permission: op
    permission-message: You do not have permission!
    usage: /checkmana
  unlockspells:
    description: check mana
    aliases: chmana
    permission: op
    permission-message: You do not have permission!
    usage: /checkmana
  wizteam:
    description: Manage teams within the game.
    usage: /wizteam <create|delete|join|leave|add|remove>
    permission: wizardsplugin.team
    permission-message: You don't have permission to use this command.
    aliases: [t]
  fillChests:
    description: Fills chests in a specified area with spells and armor.
    usage: /fillChests <x1> <y1> <z1> <x2> <y2> <z2>
  fill1:
    description: Fills chests in a specified area with spells and armor.
    usage: /fillChests <x1> <y1> <z1> <x2> <y2> <z2>
  fill2:
    description: Fills chests in a specified area with spells and armor.
    usage: /fillChests <x1> <y1> <z1> <x2> <y2> <z2>
  wizards:
    description: Fills chests in a specified area with spells and armor.
    usage: /wizards join/leave/start/stop
  setspawn:
    description: Fills chests in a specified area with spells and armor.
    usage: /setspawn



#load: POSTWORLD

#depend:

#softdepend:

#loadbefore:

#commands:
#  foo:
#    description: Foo
#    aliases:
#    permission: test.foo
#    permission-message: You do not have permission!
#    usage: /<command> [test|stop]
#permissions:
#  test.foo:
#    description: Allows foo command
#    default: op
