name: WizardsPlugin
api-version: 1.20
version: 0.18
main: WizardsGame.WizardsPlugin
description: Wizards Minigame
author: hareesun
commands:
  toggleinfinitemana:
    description: toggle infinite mana
    aliases: mana
    permission: op
    permission-message: You do not have permission!
    usage: /togglemana
  togglecooldowns:
    description: toggle infinite mana
    aliases: cooldowns
    permission: op
    permission-message: You do not have permission!
    usage: /togglecooldowns


#load: POSTWORLD

#depend:

#softdepend:

#loadbefore:

#commands:
#  foo:
#    description: Foo
#    aliases:
#    permission: test.foo
#    permission-message: You do not have permission!
#    usage: /<command> [test|stop]
#permissions:
#  test.foo:
#    description: Allows foo command
#    default: op
