name: WizardsPlugin
version: 1.0
main: WizardsGame.WizardsPlugin
description: Wizards Minigame
author: hareesun
#load: POSTWORLD

#depend:

#softdepend:

#loadbefore:

#commands:
#  foo:
#    description: Foo
#    aliases:
#    permission: test.foo
#    permission-message: You do not have permission!
#    usage: /<command> [test|stop]
#permissions:
#  test.foo:
#    description: Allows foo command
#    default: op
