name: WizardsPlugin
api-version: 1.20
version: 0.20
main: WizardsGame.WizardsPlugin
description: Wizards Minigame
author: hareesun
commands:
  toggleinfinitemana:
    description: Toggle infinite mana
    aliases: mana
    permission: op
    permission-message: You do not have permission!
    usage: /togglemana
  togglecooldowns:
    description: Toggle cooldowns
    aliases: cooldowns
    permission: op
    permission-message: You do not have permission!
    usage: /togglecooldowns
  checkmana:
    description: Check mana
    aliases: chmana
    permission: op
    permission-message: You do not have permission!
    usage: /checkmana
  unlockspells:
    description: Raise level of all spells by 1
    aliases: chmana
    permission: op
    permission-message: You do not have permission!
    usage: /checkmana
  wizteam:
    description: Manage teams within the game.
    usage: /wizteam <create|delete|join|leave|add|remove>
    permission: wizardsplugin.team
    permission-message: You don't have permission to use this command.
    aliases: [t]
  fillChests:
    description: Fills chests in a specified area with spells and armor.
    usage: /fillChests
  map1:
    description: Saves map1 location.
    usage: /map1
  map2:
    description: Saves map2 location.
    usage: /map2
  wizards:
    description: Manage minigame.
    usage: /wizards join/leave/start/stop
  setspawn:
    description: Sets spawnpoints for Wizards minigame.
    usage: /setspawn
  mapsave:
    description: Saves all blocks in the area designated by /map1 and /map2.
    usage: /setspawn
  mapregen:
    description: Regenerates all blocks within the area designated by /map1 and /map2.
    usage: /setspawn




#load: POSTWORLD

#depend:

#softdepend:

#loadbefore:

#commands:
#  foo:
#    description: Foo
#    aliases:
#    permission: test.foo
#    permission-message: You do not have permission!
#    usage: /<command> [test|stop]
#permissions:
#  test.foo:
#    description: Allows foo command
#    default: op
