name: WizardsPlugin
api-version: 1.20
version: 0.20
main: WizardsGame.WizardsPlugin
description: Wizards Minigame
author: hareesun
commands:
  toggleinfinitemana:
    description: toggle infinite mana
    aliases: mana
    permission: op
    permission-message: You do not have permission!
    usage: /togglemana
  togglecooldowns:
    description: toggle cooldowns
    aliases: cooldowns
    permission: op
    permission-message: You do not have permission!
    usage: /togglecooldowns
  checkmana:
    description: check mana
    aliases: chmana
    permission: op
    permission-message: You do not have permission!
    usage: /checkmana
  unlockspells:
    description: check mana
    aliases: chmana
    permission: op
    permission-message: You do not have permission!
    usage: /checkmana
  wizteam:
    description: Manage teams within the game.
    usage: /wizteam <create|delete|join|leave|add|remove>
    permission: wizardsplugin.team
    permission-message: You don't have permission to use this command.
    aliases: [t]

#  wizteam create:
#    description: Create a new team.
#    usage: /wizteam create <Team name>
#    permission: wizardsplugin.team.create
#    permission-message: You don't have permission to create a team.
#
#  wizteam delete:
#    description: Delete an existing team.
#    usage: /wizteam delete <Team name>
#    permission: wizardsplugin.team.delete
#    permission-message: You don't have permission to delete a team.
#
#  wizteam join:
#    description: Join a specified team.
#    usage: /wizteam join <Team name>
#    permission: wizardsplugin.team.join
#    permission-message: You don't have permission to join this team.
#
#  wizteam leave:
#    description: Leave your current team.
#    usage: /wizteam leave
#    permission: wizardsplugin.team.leave
#    permission-message: You don't have permission to leave your team.
#
#  wizteam add:
#    description: Add a player to a team.
#    usage: /wizteam add <Player name> <Team name>
#    permission: wizardsplugin.team.add
#    permission-message: You don't have permission to add a player to a team.
#
#  wizteam remove:
#    description: Remove a player from a team.
#    usage: /wizteam remove <Player name> <Team name>
#    permission: wizardsplugin.team.remove
#    permission-message: You don't have permission to remove a player from a team.





#load: POSTWORLD

#depend:

#softdepend:

#loadbefore:

#commands:
#  foo:
#    description: Foo
#    aliases:
#    permission: test.foo
#    permission-message: You do not have permission!
#    usage: /<command> [test|stop]
#permissions:
#  test.foo:
#    description: Allows foo command
#    default: op
